# Generated by Django 6.0.2 on 2026-02-26 18:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('terminee', 'Terminée')], default='en_cours', max_length=20, verbose_name='Statut')),
                ('priorite', models.CharField(choices=[('faible', 'Faible'), ('moyenne', 'Moyenne'), ('haute', 'Haute')], default='moyenne', max_length=20, verbose_name='Priorité')),
            ],
            options={
                'verbose_name': 'Tâche',
                'verbose_name_plural': 'Tâches',
                'ordering': ['-date_creation'],
            },
        ),
    ]
